---
title: "Intial Exploration of Data"
author: "Calvin Skalla"
date: "3/17/2020"
output: html_document
---

# Data Exploration and Cleaning
```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(knitr)
library(ggthemes)
library(cowplot)
library(ggridges)

white_wine <- read.csv("data/winequality-white.csv", sep = ";")
white_wine <- mutate(white_wine, Type = "white") 

red_wine <- read.csv("data/winequality-red.csv", sep = ";")
red_wine <- mutate(red_wine, Type = "red")

wine_data <- rbind(white_wine, red_wine) %>% mutate(Like = as.factor(ifelse(quality >5, "good", "bad")), Quality = as.factor(quality)) %>% select(-quality)


```

# Distributions of Variables
```{r, echo=FALSE, message=FALSE}
#ww_dist <- count(white_wine, white_wine$quality)
#rw_dist <- count(red_wine, red_wine$quality)
#wine_dist <- merge(ww_dist, rw_dist, by = "quality", all.x = TRUE)
#colnames(wine_dist) = c("Quality", "White", "Red")


#kbl <- knitr::kable(wine_dist, format = "html")
#kableExtra::kable_styling(kbl, full_width = FALSE)

#ggplot(wine_data, aes(x = Quality, fill = Type)) + geom_bar(position = "stack") + geom_text(aes(y = agreggated$amount, data = agreggated))

#geom_text(aes(x = Quality, y = amount, label = amount), vjust = -0.25)

#Works in Progress below: might delete and use density ridges instead because of readability
ggplot(wine_data) + geom_density(aes(x = fixed.acidity, y = ..density..)) + facet_wrap(~Quality)

ggplot(wine_data) + geom_density(aes(x = volatile.acidity, y = ..density..)) + facet_wrap(~Quality)

hist(wine_data$citric.acid)

ggplot(wine_data) + geom_density(aes(x = residual.sugar)) + facet_wrap(~Quality)

hist(wine_data$chlorides)
hist(wine_data$free.sulfur.dioxide)
hist(wine_data$total.sulfur.dioxide)
hist(wine_data$density)
hist(wine_data$pH)
hist(wine_data$sulphates)
ggplot(wine_data) + geom_density(aes(x = alcohol)) + facet_wrap(~Quality)

```

Quality ~ volatile.acidity + residual.sugar + alcohol
#  geom_point & geom_line
## White wine
```{r, echo=FALSE, message=FALSE, include=FALSE}
fix_acid_summary <- white_wine %>% group_by(quality) %>% summarise(fixed.acidity = mean(fixed.acidity))

ggplot(white_wine, aes(x = quality, y = fixed.acidity)) + geom_point(alpha = 1/10, position = position_jitter(height = 0.2, width = 0.2)) + geom_line(data = fix_acid_summary, size = 2) + geom_point(data = fix_acid_summary, size = 4, color = "maroon")

vol_acid_summary <- white_wine %>% group_by(quality) %>% summarise(volatile.acidity = mean(volatile.acidity))
ggplot(white_wine, aes(x = quality, y = volatile.acidity)) + geom_point(alpha = 1/10, position = position_jitter(height = 0.2, width = 0.2)) + geom_line(data = vol_acid_summary, size = 2) + geom_point(data = vol_acid_summary, size = 4, color = "maroon")

citric_acid_summary <- white_wine %>% group_by(quality) %>% summarise(citric.acid = mean(citric.acid))
ggplot(white_wine, aes(x = quality, y = citric.acid)) + geom_point(alpha = 1/10, position = position_jitter(height = 0.2, width = 0.2)) + geom_line(data = citric_acid_summary, size = 2) + geom_point(data = citric_acid_summary, size = 4, color = "maroon")

density_summary <- white_wine %>% group_by(quality) %>% summarise(density = mean(density))
ggplot(white_wine, aes(x = quality, y = density)) + geom_point(alpha = 1/10, position = position_jitter(height = 0.2, width = 0.2)) + geom_line(data = density_summary, size = 2) + geom_point(data = density_summary, size = 4, color = "maroon")

alcohol_summary <- white_wine %>% group_by(quality) %>% summarise(alcohol = mean(alcohol))
ggplot(white_wine, aes(x = quality, y = alcohol)) + geom_point(alpha = 1/10, position = position_jitter(height = 0.2, width = 0.2)) + geom_line(data = alcohol_summary, size = 2) + geom_point(data = alcohol_summary, size = 4, color = "maroon")

alcohol_summary
```

# Density Ridges Graphs
## Using quality data
```{r, echo=FALSE, message=FALSE}
gg5 <- ggplot(wine_data) + geom_density_ridges(aes(x = volatile.acidity, y = Quality))

gg6 <- ggplot(wine_data) + geom_density_ridges(aes(x = alcohol, y = Quality))

ggplot(wine_data) + geom_density_ridges(aes(x = residual.sugar, y = Quality))

```

## Using Like data
```{r, echo=FALSE, message=FALSE}
ggplot(wine_data) + geom_density(aes(x = alcohol, fill = Like), alpha = 0.2)

ggplot(wine_data) + geom_density(aes(x = volatile.acidity, fill = Like), alpha = 0.2)

ggplot(wine_data) + geom_density(aes(x = residual.sugar, fill = Like), alpha = 0.2)
```


```{r, echo=FALSE, message=FALSE}
gplot <- ggplot(wine_data, aes(x = volatile.acidity, y = residual.sugar, color = alcohol)) + geom_point(data = white_wine, color = "grey80") + geom_point(size = 2.5) + facet_wrap(~Quality)
gplot
```


# Boxplots
```{r, echo=FALSE, message=FALSE}
bp1 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = pH))
bp2 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = density))
bp3 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = alcohol))
bp4 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = sulphates))
bp5 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = total.sulfur.dioxide))
bp6 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = free.sulfur.dioxide))
bp7 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = chlorides))
bp8 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = residual.sugar))
bp9 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = citric.acid))
bp10 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = volatile.acidity))
bp11 <- ggplot(wine_data) + geom_boxplot(aes(x = Quality, y = fixed.acidity))
plot_grid(bp1, bp2, bp3, bp4, bp5, bp6, bp7, bp8, bp9, bp10, bp11, ncol = 3)

```


